services:
  backend:
    build: 
      context: ./portfolio_tracker_api # Path to backend docker file
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - "./portfolio_tracker_api/.env"
    volumes:
      - ./portfolio_tracker_api/staticfiles:/app/staticfiles  # Correct static files mount
      - ./portfolio_tracker_api:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    env_file:
      - "./portfolio_tracker_api/.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
  
  nginx:
    build:
      context: . # context is root
      dockerfile: ./nginx/dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./portfolio_tracker_api/staticfiles:/app/staticfiles  # Correct static files mount
  
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

    