# Use the official Python image as a base
FROM python:3.10-slim AS backend-stage

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /app

# Install dependencies
# COPY requirements.txt /app/
# Copy the project files
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt

#Collect static files for nginx
RUN python manage.py collectstatic --noinput && \
    chmod -R 755 /app/staticfiles && \
    chown -R www-data:www-data /app/staticfiles


# Expose the port the app runs on
EXPOSE 8000

# # Run the application and serve static files
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# Run Gunicorn as the WSGI server
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "portfolio_tracker.wsgi:application"]