# Stage 1: Build the Vue.js frontend
FROM node:24-slim AS build-stage
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY ../portfolio-frontend/package*.json ./
RUN npm install

# Copy the rest of the application code
COPY ../portfolio-frontend ./

# Build the Vue.js application
RUN npm run build

# Stage 2: Serve the built files with Nginx
FROM nginx:alpine

# Correctly reference the default.conf file in the nginx directory
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy the built files from the build stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Copy entrypoint script
COPY ./nginx/nginx-entrypoint.sh /nginx-entrypoint.sh
RUN chmod +x /nginx-entrypoint.sh

# Expose port 80 for the Nginx server
EXPOSE 80

# Start Nginx
CMD ["/nginx-entrypoint.sh"]