FROM nginx:alpine

# Correctly reference the default.conf file in the nginx directory
COPY ./nginx/dev.conf /etc/nginx/conf.d/default.conf

# Copy entrypoint script
COPY ./nginx/nginx-entrypoint.sh /nginx-entrypoint.sh
RUN chmod +x /nginx-entrypoint.sh

# Expose port 80 for the Nginx server
EXPOSE 80

# Start Nginx
CMD ["/nginx-entrypoint.sh"]